name: Repo Visualizer

on:
  push:
    branches: [main]  # change to 'master' or 'dev' if your branch is different

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate repo diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "diagram.svg"
          excluded_paths: "node_modules,.github,build"
          should_push: true
          commit_message: "add: repo diagram [skip ci]"
